In [1]:
import numpy as np

In [ ]:
arr = np.arange(16)

print("Array: ", arr)
print("Slicing: ", arr[1:5])
print("Slicing with step: ", arr[1: 13: 2])

print("Negative index: ", arr[-2])
print("Neg step: ", arr[::-1])
print("Neg step: ", arr[:-10:-2])

Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Slicing:  [1 2 3 4]
Slicing with step:  [ 1  3  5  7  9 11]
Negative index:  14
Neg step:  [15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]
Neg step:  [15 13 11  9  7]


### SLicing

In [18]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Specific element", arr_2d[2, 2])
print("Entire row: ", arr_2d[1])
print("Entire Column: ", arr_2d[:, 1])

Specific element 9
Entire row:  [4 5 6]
Entire Column:  [2 5 8]


### Sorting

In [23]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Sorted Array: ", np.sort(unsorted))

arr_2d = np.array([[51, 22, 43],
                   [43, 95, 69],
                   [37, 83, 59]])
print("Sorted Row wise\n", np.sort(arr_2d, axis=1))
print("Sorted Column wise\n", np.sort(arr_2d, axis=0))

Sorted Array:  [1 1 2 3 4 5 6 9]
Sorted Row wise
 [[22 43 51]
 [43 69 95]
 [37 59 83]]
Sorted Column wise
 [[37 22 43]
 [43 83 59]
 [51 95 69]]


### Filter

In [36]:
numbers = np.array([10, 21, 35, 40, 54, 63, 76, 87, 96, 110])
even_number = numbers[numbers %2 ==0]
print("Even numbers: ", even_number)

Even numbers:  [ 10  40  54  76  96 110]


### Fancy indexing and np.where()

In [37]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 50)
print(where_result)
print("NP where: ", numbers[where_result])


[10 35 54]
(array([4, 5, 6, 7, 8, 9]),)
NP where:  [ 54  63  76  87  96 110]


In [39]:
condition_array = np.where(numbers > 50, "true", "false")
print(condition_array)

# Above works like below
# if numbers > 50:
#     "true"
# else:
#     "false"

['false' 'false' 'false' 'false' 'true' 'true' 'true' 'true' 'true' 'true']


In [41]:
print("Numbers: ", numbers)
condition_array2 = np.where(numbers > 50, numbers*10, numbers)
print(condition_array2)

Numbers:  [ 10  21  35  40  54  63  76  87  96 110]
[  10   21   35   40  540  630  760  870  960 1100]


### Adding and removing data

In [43]:
arr1 = np.array([1, 2 ,3])
arr2 = np.array([4, 5, 6])

print("Concatenated: ", np.concatenate((arr1, arr2)))


Concatenated:  [1 2 3 4 5 6]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9, 7])

print("SHape Compatibilty a & b: ", a.shape == b.shape)
print("SHape Compatibilty a & c: ", a.shape == c.shape)
print("Shape of a, b , c: ", a.shape, b.shape, c.shape)

SHape Compatibilty a & b:  True
SHape Compatibilty a & c:  False
Shape of a, b , c:  1 (3,) (4,)


In [66]:
arr = np.array([[1,2], [3,4]])
print(arr)
print("Shape: ", arr.shape)

new_row = np.array([[7,5], [5, 7]])
with_new_row = np.vstack((arr, new_row))
print("\n\nWith New Row\n", with_new_row)
print("New Shape: ", with_new_row.shape)

new_col = np.array([[7,5], [5, 7]])
with_new_col = np.hstack((arr, new_col))
print("\n\nWith New Col\n", with_new_col)
print("New Shape: ", with_new_col.shape)

[[1 2]
 [3 4]]
Shape:  (2, 2)


With New Row
 [[1 2]
 [3 4]
 [7 5]
 [5 7]]
New Shape:  (4, 2)


With New Col
 [[1 2 7 5]
 [3 4 5 7]]
New Shape:  (2, 4)
