In [2]:
import numpy as np
import matplotlib.pyplot as plt

Matplotlib is building the font cache; this may take a moment.


In [5]:
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

print("Sales data shape: ", sales_data.shape)
print("\n Sample data for 1st 3 restau: \n", sales_data[:3])

Sales data shape:  (5, 5)

 Sample data for 1st 3 restau: 
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]


In [ ]:
print("Total sales per year: \n")
# Method 1
print(np.sum(sales_data, axis=0)[1:])
# Method 2
print(np.sum(sales_data[:, 1:], axis=0))

print("\nMin sales per restaurant: ")
print(np.min(sales_data[:, 1:], axis=1))

print("\nMax sales per year:")
print(np.max(sales_data[:, 1:], axis=0))

print("\nAvg sales per restaurant:")
print(np.mean(sales_data[: , 1:], axis=1))

Total sales per year: 

[ 810000  945000 1085000 1240000]
[ 810000  945000 1085000 1240000]

Min sales per restaurant: 
[150000 120000 200000 180000 160000]

Max sales per year:
[200000 230000 260000 300000]

Avg sales per restaurant
[200000. 152500. 247500. 225000. 195000.]
