In [3]:
import numpy as np

In [4]:
arr_1d = np.array([1, 2, 3, 4,5])
print("1D Array")
print(arr_1d)

arr_2d = np.array([[1, 2, 3,4], [5, 6, 7, 8]])
print("2D Array")
print(arr_2d)

1D Array
[1 2 3 4 5]
2D Array
[[1 2 3 4]
 [5 6 7 8]]


In [5]:
list = [1, 2 ,4 ,5]
print("Python List Multiplication: ", list*2)

arr = np.array([1, 2, 4, 5])
print("Numpy Array Multiplication: ", arr*2)

Python List Multiplication:  [1, 2, 4, 5, 1, 2, 4, 5]
Numpy Array Multiplication:  [ 2  4  8 10]


In [6]:
import time

start = time.time()
list = [i*2 for i in range(100000000)]
print("Standard Python List Time : ", time.time() - start)

start = time.time()
np_arr = np.arange(100000000)*2
print("Numpy List Time : ", time.time() - start)



Standard Python List Time :  1.4558179378509521
Numpy List Time :  0.2577798366546631


### Creating Arrays

In [7]:
zeros_1d = np.zeros(3)
print("1D Zero Array")
print(zeros_1d)

zeros_2d = np.zeros((3,4))
print("2D Zero Array")
print(zeros_2d)

ones = np.ones((4,5))
print("Ones Array")
print(ones)

full = np.full((3, 3), 9)
print("Full Array")
print(full)

random = np.random.random((2,3))
print("Random Array \n", random)

sequence = np.arange(0, 11, 2)
print("Sequence\n", sequence)
sequence = np.arange(10, 40)
print("Sequence\n", sequence)

1D Zero Array
[0. 0. 0.]
2D Zero Array
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Full Array
[[9 9 9]
 [9 9 9]
 [9 9 9]]
Random Array 
 [[0.71141124 0.59482925 0.80364567]
 [0.33417725 0.39469104 0.71192678]]
Sequence
 [ 0  2  4  6  8 10]
Sequence
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39]


In [8]:
tensor = np.array([[[1, 2, 3], [3, 4, 7]], 
                   [[5, 6, 8], [7, 8, 24]]])
print(tensor.shape)
print(tensor.ndim)

(2, 2, 3)
3


### Array Properties

In [9]:
arr = np.array([[1, 2, 3, 4], 
                [5, 6, 7, 8]])

print("Shape: ", arr.shape)
print("Dimension: ", arr.ndim)
print("Dtype: ", arr.dtype)

Shape:  (2, 4)
Dimension:  2
Dtype:  int64


In [10]:
a = np.arange(12)
print("Original Array: ", a)

reshaped = a.reshape((4,3))
print("\nReshaped Array: \n", reshaped)

# Returns copy
flatten = reshaped.flatten()
print("\nFlattened Array: ", flatten)

# Returns view instead of copy
ravel = reshaped.ravel()
print("\nRavel Array: ", ravel)

transpose = reshaped.T
print("\nTranspose: \n", transpose)


Original Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped Array: 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Flattened Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Ravel Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Transpose: 
 [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [11]:
arr= np.array([[[1,7],[2,7]], 
               [[4,7],[5,7]], 
               [[7,7],[8,7]]])
print(arr)
print(arr.ndim)
print(arr.shape)

[[[1 7]
  [2 7]]

 [[4 7]
  [5 7]]

 [[7 7]
  [8 7]]]
3
(3, 2, 2)
